### ISSUE TITLE
Crash direkt nach Start: UnsupportedOperationException

### ISSUE THREAD

**Issue by grote** [boombuler/piraten_map_app#8]
Wurde mir per E-Mail zugesandt und kann ich selbst nicht reproduzieren:

Sony ericson Xperia mini
Android ist 4.0.4

``````
E/AndroidRuntime( 2019): java.lang.UnsupportedOperationException
E/AndroidRuntime( 2019):        at android.view.GLES20Canvas.drawPicture(GLES20Canvas.java:899)
E/AndroidRuntime( 2019):        at org.osmdroid.views.overlay.MyLocationOverlay.drawCompass(MyLocationOverlay.java:352)
E/AndroidRuntime( 2019):        at org.osmdroid.views.overlay.MyLocationOverlay.draw(MyLocationOverlay.java:379)
E/AndroidRuntime( 2019):        at org.osmdroid.views.overlay.OverlayManager.onDraw(OverlayManager.java:141)
E/AndroidRuntime( 2019):        at org.osmdroid.views.MapView.dispatchDraw(MapView.java:1024)
E/AndroidRuntime( 2019):        at android.view.View.getDisplayList(View.java:10519)
E/AndroidRuntime( 2019):        at android.view.ViewGroup.drawChild(ViewGroup.java:2954)
E/AndroidRuntime( 2019):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2593)
E/AndroidRuntime( 2019):        at android.view.View.getDisplayList(View.java:10519)
E/AndroidRuntime( 2019):        at android.view.ViewGroup.drawChild(ViewGroup.java:2954)
E/AndroidRuntime( 2019):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2593)
E/AndroidRuntime( 2019):        at android.view.View.getDisplayList(View.java:10519)
E/AndroidRuntime( 2019):        at android.view.ViewGroup.drawChild(ViewGroup.java:2954)
E/AndroidRuntime( 2019):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2593)
E/AndroidRuntime( 2019):        at android.view.View.getDisplayList(View.java:10519)
E/AndroidRuntime( 2019):        at android.view.ViewGroup.drawChild(ViewGroup.java:2954)
E/AndroidRuntime( 2019):        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2593)
E/AndroidRuntime( 2019):        at android.view.View.draw(View.java:11085)
E/AndroidRuntime( 2019):        at android.widget.FrameLayout.draw(FrameLayout.java:462)
E/AndroidRuntime( 2019):        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2145)
E/AndroidRuntime( 2019):        at android.view.View.getDisplayList(View.java:10521)
E/AndroidRuntime( 2019):        at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:851)
E/AndroidRuntime( 2019):        at android.view.ViewRootImpl.draw(ViewRootImpl.java:1910)
E/AndroidRuntime( 2019):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1634)
E/AndroidRuntime( 2019):        at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2442)
E/AndroidRuntime( 2019):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2019):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 2019):        at android.app.ActivityThread.main(ActivityThread.java:4441)
E/AndroidRuntime( 2019):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2019):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 2019):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime( 2019):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime( 2019):        at dalvik.system.NativeStart.main(Native Method)
I/Process ( 2019): Sending signal. PID: 2019 SIG: 9
I/ActivityManager( 281): Process com.boombuler.piraten.map (pid 2019) has died.```
``````

**Comment by DJaeger** [comment]
Der Crash wird verursacht durch osmdroid bei Hardwarebeschleunigung
Der Fehler ist in der neuesten Version (5.6.1) von osmdroid behoben worden
